from django.test import TestCase

from apps.catalog.models import Card, CardSet, GradingCompany, Player, PriceObservation
from apps.catalog.services import constants


class ModelTests(TestCase):
    def test_player_slug_autogenerated(self):
        player = Player.objects.create(name='Ja Morant', sport=constants.SPORT_BASKETBALL)
        self.assertEqual(player.slug, 'ja-morant-basketball')

    def test_card_set_slug_and_display(self):
        cs = CardSet.objects.create(
            year=2018, brand='Panini', name='Prizm', sport=constants.SPORT_BASKETBALL
        )
        self.assertEqual(cs.slug, '2018-panini-prizm-basketball')
        self.assertEqual(cs.display_name, '2018 Panini Prizm')

    def test_canonical_key_is_deterministic(self):
        key1 = Card.build_canonical_key('2018-panini-prizm-basketball', '280', 'Silver', 'luka-doncic-basketball')
        key2 = Card.build_canonical_key('2018-panini-prizm-basketball', '280', 'Silver', 'luka-doncic-basketball')
        self.assertEqual(key1, key2)

    def test_canonical_key_defaults_for_missing_parts(self):
        key = Card.build_canonical_key('2018-panini-prizm-basketball', None, None, None)
        self.assertIn('base', key)
        self.assertIn('unknown-player', key)

    def test_price_observation_str(self):
        cs = CardSet.objects.create(year=2018, brand='Panini', name='Prizm', sport='BASKETBALL')
        card = Card.objects.create(card_set=cs, canonical_key='k-1', card_number='280')
        obs = PriceObservation.objects.create(
            card=card, source='ebay', price='250.00', grade='10'
        )
        self.assertIn('ebay', str(obs))
        self.assertIn('250', str(obs))

    def test_grading_company_unique_code(self):
        GradingCompany.objects.create(code='PSA', name='Professional Sports Authenticator')
        with self.assertRaises(Exception):
            GradingCompany.objects.create(code='PSA', name='dup')
