# Generated by Django 5.2.15 on 2026-06-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has confirmed their email address",
                verbose_name="Email Verified",
            ),
        ),
    ]
