# Generated by Django 5.2.7 on 2025-11-12 23:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=500, verbose_name='Search Query')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], default='PENDING', max_length=20, verbose_name='Status')),
                ('player_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Player Name')),
                ('card_year', models.IntegerField(blank=True, null=True, verbose_name='Card Year')),
                ('card_set', models.CharField(blank=True, max_length=200, null=True, verbose_name='Card Set')),
                ('grade', models.CharField(blank=True, help_text='PSA 10, BGS 9.5, etc.', max_length=50, null=True, verbose_name='Grade')),
                ('total_sites', models.IntegerField(default=0, help_text='Total number of sites queried', verbose_name='Total Sites')),
                ('successful_sites', models.IntegerField(default=0, help_text='Number of sites that returned results', verbose_name='Successful Sites')),
                ('failed_sites', models.IntegerField(default=0, help_text='Number of sites that failed', verbose_name='Failed Sites')),
                ('total_items_found', models.IntegerField(default=0, help_text='Total number of items found across all sites', verbose_name='Total Items Found')),
                ('execution_time_seconds', models.FloatField(blank=True, help_text='Total execution time in seconds', null=True, verbose_name='Execution Time (s)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searches',
                'db_table': 'searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=500, verbose_name='Search Query')),
                ('was_successful', models.BooleanField(default=False, help_text='Whether the search completed successfully', verbose_name='Was Successful')),
                ('total_results', models.IntegerField(default=0, help_text='Total number of results found', verbose_name='Total Results')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Accessed At')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='search.search', verbose_name='Search')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Search History Entry',
                'verbose_name_plural': 'Search History',
                'db_table': 'search_history',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Site Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('base_url', models.URLField(verbose_name='Base URL')),
                ('site_type', models.CharField(choices=[('SALES', 'Sales Platform'), ('AUCTION', 'Auction House'), ('POPULATION', 'Population Data'), ('MARKETPLACE', 'Marketplace')], default='SALES', max_length=20, verbose_name='Site Type')),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20, verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('agent_class_name', models.CharField(help_text='Name of the agent class (e.g., EbayAgent)', max_length=100, verbose_name='Agent Class Name')),
                ('timeout_seconds', models.IntegerField(default=30, help_text='Timeout in seconds for scraping this site', verbose_name='Timeout (seconds)')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum number of retry attempts', verbose_name='Max Retries')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Target Site',
                'verbose_name_plural': 'Target Sites',
                'db_table': 'target_sites',
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['slug'], name='target_site_slug_95b7b4_idx'), models.Index(fields=['is_active'], name='target_site_is_acti_66c291_idx'), models.Index(fields=['priority'], name='target_site_priorit_fed086_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScrapeResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout'), ('NO_RESULTS', 'No Results')], max_length=20, verbose_name='Status')),
                ('data', models.JSONField(default=dict, help_text='Scraped data in JSON format', verbose_name='Data')),
                ('items_count', models.IntegerField(default=0, help_text='Number of items found', verbose_name='Items Count')),
                ('execution_time_seconds', models.FloatField(blank=True, help_text='Execution time for this site in seconds', null=True, verbose_name='Execution Time (s)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts made', verbose_name='Retry Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='search.search', verbose_name='Search')),
                ('target_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='search.targetsite', verbose_name='Target Site')),
            ],
            options={
                'verbose_name': 'Scrape Result',
                'verbose_name_plural': 'Scrape Results',
                'db_table': 'scrape_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['user', '-created_at'], name='searches_user_id_a104dd_idx'),
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['status'], name='searches_status_11713b_idx'),
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['player_name'], name='searches_player__82c0aa_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', '-accessed_at'], name='search_hist_user_id_d84211_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['query'], name='search_hist_query_69a772_idx'),
        ),
        migrations.AddIndex(
            model_name='scraperesult',
            index=models.Index(fields=['search', '-created_at'], name='scrape_resu_search__30bc52_idx'),
        ),
        migrations.AddIndex(
            model_name='scraperesult',
            index=models.Index(fields=['target_site', 'status'], name='scrape_resu_target__00e972_idx'),
        ),
        migrations.AddIndex(
            model_name='scraperesult',
            index=models.Index(fields=['status'], name='scrape_resu_status_142064_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scraperesult',
            unique_together={('search', 'target_site')},
        ),
    ]
