# Generated by Django 5.2.15 on 2026-06-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="celery_task_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ID of the Celery task processing this search (for cancellation)",
                max_length=255,
                verbose_name="Celery Task ID",
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("PARTIAL", "Partial Success"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
