# Generated by Django 5.2.7 on 2025-11-13 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Sports Card KickOff', help_text='Name of the application', max_length=100, verbose_name='Site Name')),
                ('site_description', models.TextField(default='Professional sports card price aggregator and market analysis platform', help_text='Brief description of the platform', verbose_name='Site Description')),
                ('site_logo', models.ImageField(blank=True, help_text='Main logo for the application', null=True, upload_to='core/logos/', verbose_name='Site Logo')),
                ('site_favicon', models.ImageField(blank=True, help_text='Favicon icon (32x32 or 64x64)', null=True, upload_to='core/favicons/', verbose_name='Favicon')),
                ('meta_keywords', models.CharField(default='sports cards, PSA, grading, card prices, market analysis', help_text='SEO keywords (comma separated)', max_length=255, verbose_name='Meta Keywords')),
                ('meta_author', models.CharField(default='Sports Card KickOff Team', max_length=100, verbose_name='Meta Author')),
                ('og_image', models.ImageField(blank=True, help_text='Image for social media sharing (1200x630)', null=True, upload_to='core/og-images/', verbose_name='Open Graph Image')),
                ('contact_email', models.EmailField(default='contact@sportscardkickoff.com', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Contact Email')),
                ('support_email', models.EmailField(default='support@sportscardkickoff.com', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Support Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('address', models.TextField(blank=True, verbose_name='Physical Address')),
                ('twitter_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='Twitter/X URL')),
                ('facebook_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='LinkedIn URL')),
                ('openai_api_key', models.CharField(blank=True, help_text='API key for OpenAI/ChatGPT (for LLM-based scraping)', max_length=512, verbose_name='OpenAI API Key')),
                ('openai_org_id', models.CharField(blank=True, help_text='Optional: OpenAI organization ID', max_length=512, verbose_name='OpenAI Organization ID')),
                ('anthropic_api_key', models.CharField(blank=True, help_text='API key for Claude (alternative LLM)', max_length=512, verbose_name='Anthropic API Key')),
                ('google_api_key', models.CharField(blank=True, help_text='API key for Google Gemini models', max_length=512, verbose_name='Google AI API Key')),
                ('huggingface_api_key', models.CharField(blank=True, help_text='API key for HuggingFace Inference API (optional)', max_length=512, verbose_name='HuggingFace API Key')),
                ('default_llm_model', models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini (Recommended)'), ('gpt-4o', 'GPT-4o (High Precision)'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'), ('claude-3-opus-20240229', 'Claude 3 Opus'), ('claude-3-haiku-20240307', 'Claude 3 Haiku'), ('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Fast & Cheap)'), ('gemini-1.0-pro', 'Gemini 1.0 Pro'), ('meta-llama/Meta-Llama-3-70B-Instruct', 'Llama 3 70B'), ('mistralai/Mistral-7B-Instruct-v0.2', 'Mistral 7B')], default='gpt-4o-mini', help_text='Default model for LLM-based scraping', max_length=100, verbose_name='Default LLM Model')),
                ('llm_temperature', models.FloatField(default=0.0, help_text='Temperature for LLM (0 = deterministic, 1 = creative)', verbose_name='LLM Temperature')),
                ('llm_max_tokens', models.IntegerField(default=4000, help_text='Maximum tokens for LLM output', verbose_name='LLM Max Tokens')),
                ('use_llm_by_default', models.BooleanField(default=True, help_text='Enable LLM extraction by default for scraping', verbose_name='Use LLM by Default')),
                ('use_traditional_fallback', models.BooleanField(default=True, help_text='Fallback to BeautifulSoup if LLM fails', verbose_name='Use Traditional Fallback')),
                ('scraping_timeout', models.IntegerField(default=30000, help_text='Timeout in milliseconds for scraping requests', verbose_name='Scraping Timeout (ms)')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum retry attempts for failed scraping', verbose_name='Max Retries')),
                ('enable_user_registration', models.BooleanField(default=True, help_text='Allow new users to register', verbose_name='Enable User Registration')),
                ('enable_email_notifications', models.BooleanField(default=True, help_text='Send email notifications to users', verbose_name='Enable Email Notifications')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode (site unavailable)', verbose_name='Maintenance Mode')),
                ('maintenance_message', models.TextField(default='Site is currently under maintenance. Please check back soon.', help_text='Message to show during maintenance mode', verbose_name='Maintenance Message')),
                ('google_analytics_id', models.CharField(blank=True, help_text='GA tracking ID (e.g., G-XXXXXXXXXX)', max_length=50, verbose_name='Google Analytics ID')),
                ('google_tag_manager_id', models.CharField(blank=True, help_text='GTM container ID (e.g., GTM-XXXXXXX)', max_length=50, verbose_name='Google Tag Manager ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
