# Generated by Django 5.2.7 on 2025-11-13 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='site_favicon',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='site_logo',
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='apple_store_url',
            field=models.URLField(blank=True, help_text='URL to the iOS app in Apple App Store', validators=[django.core.validators.URLValidator()], verbose_name='Apple App Store URL'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='google_play_url',
            field=models.URLField(blank=True, help_text='URL to the Android app in Google Play Store', validators=[django.core.validators.URLValidator()], verbose_name='Google Play Store URL'),
        ),
    ]
