# Generated by Django 5.2.7 on 2025-11-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_logo_favicon_add_app_store_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='og_image',
        ),
    ]
