# Generated by Django 5.2.15 on 2026-06-17 11:58

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_og_image_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemconfiguration",
            name="anthropic_api_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="API key for Claude (alternative LLM)",
                verbose_name="Anthropic API Key",
            ),
        ),
        migrations.AlterField(
            model_name="systemconfiguration",
            name="google_api_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="API key for Google Gemini models",
                verbose_name="Google AI API Key",
            ),
        ),
        migrations.AlterField(
            model_name="systemconfiguration",
            name="huggingface_api_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="API key for HuggingFace Inference API (optional)",
                verbose_name="HuggingFace API Key",
            ),
        ),
        migrations.AlterField(
            model_name="systemconfiguration",
            name="openai_api_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="API key for OpenAI/ChatGPT (for LLM-based scraping)",
                verbose_name="OpenAI API Key",
            ),
        ),
        migrations.AlterField(
            model_name="systemconfiguration",
            name="openai_org_id",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="Optional: OpenAI organization ID",
                verbose_name="OpenAI Organization ID",
            ),
        ),
    ]
