# Generated by Django 5.2.15 on 2026-06-16 19:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GradingCompany",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Grading Company",
                "verbose_name_plural": "Grading Companies",
                "db_table": "catalog_grading_companies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CardSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Year")),
                ("brand", models.CharField(max_length=80, verbose_name="Brand")),
                (
                    "name",
                    models.CharField(
                        help_text='Product line, e.g. "Prizm", "Chrome"',
                        max_length=120,
                        verbose_name="Set Name",
                    ),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("BASKETBALL", "Basketball"),
                            ("FOOTBALL", "Football"),
                            ("BASEBALL", "Baseball"),
                            ("HOCKEY", "Hockey"),
                            ("SOCCER", "Soccer"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Sport",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Card Set",
                "verbose_name_plural": "Card Sets",
                "db_table": "catalog_card_sets",
                "ordering": ["-year", "brand", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="catalog_car_slug_161522_idx"),
                    models.Index(fields=["year"], name="catalog_car_year_e1bdbf_idx"),
                    models.Index(fields=["brand"], name="catalog_car_brand_486f4d_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "brand", "name", "sport"), name="uniq_card_set"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(max_length=180, unique=True, verbose_name="Slug"),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("BASKETBALL", "Basketball"),
                            ("FOOTBALL", "Football"),
                            ("BASEBALL", "Baseball"),
                            ("HOCKEY", "Hockey"),
                            ("SOCCER", "Soccer"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Sport",
                    ),
                ),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Alternate spellings/nicknames used in listings",
                        verbose_name="Aliases",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Player",
                "verbose_name_plural": "Players",
                "db_table": "catalog_players",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="catalog_pla_slug_583faa_idx"),
                    models.Index(fields=["sport"], name="catalog_pla_sport_50e665_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Card Number"
                    ),
                ),
                (
                    "parallel",
                    models.CharField(
                        blank=True,
                        help_text='Parallel/variation, e.g. "Silver", "Refractor"',
                        max_length=80,
                        verbose_name="Parallel",
                    ),
                ),
                (
                    "is_rookie",
                    models.BooleanField(default=False, verbose_name="Rookie"),
                ),
                (
                    "is_autograph",
                    models.BooleanField(default=False, verbose_name="Autograph"),
                ),
                (
                    "is_memorabilia",
                    models.BooleanField(default=False, verbose_name="Memorabilia"),
                ),
                (
                    "serial_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Print run limit, e.g. 99 for a /99 parallel",
                        null=True,
                        verbose_name="Serial Limit",
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Extra Attributes"
                    ),
                ),
                (
                    "canonical_key",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="Canonical Key"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="catalog.cardset",
                        verbose_name="Card Set",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cards",
                        to="catalog.player",
                        verbose_name="Player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card",
                "verbose_name_plural": "Cards",
                "db_table": "catalog_cards",
                "ordering": ["card_set", "card_number"],
            },
        ),
        migrations.CreateModel(
            name="PriceObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text='Source identifier, e.g. "ebay"',
                        max_length=40,
                        verbose_name="Source",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("LISTING", "Active Listing"),
                            ("SOLD", "Sold / Completed"),
                            ("AUCTION", "Auction"),
                        ],
                        default="LISTING",
                        max_length=20,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text='Grade value, e.g. "10", "9.5". Blank for raw.',
                        max_length=10,
                        verbose_name="Grade",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=600, verbose_name="Source URL"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="External ID"
                    ),
                ),
                ("raw_title", models.TextField(blank=True, verbose_name="Raw Title")),
                (
                    "match_confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="Resolver confidence that this observation maps to the card",
                        verbose_name="Match Confidence",
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Observed At"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_observations",
                        to="catalog.card",
                        verbose_name="Card",
                    ),
                ),
                (
                    "grading_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_observations",
                        to="catalog.gradingcompany",
                        verbose_name="Grading Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Observation",
                "verbose_name_plural": "Price Observations",
                "db_table": "catalog_price_observations",
                "ordering": ["-observed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["canonical_key"], name="catalog_car_canonic_37bfc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["card_set", "card_number"],
                name="catalog_car_card_se_b43964_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["player"], name="catalog_car_player__76d0a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="priceobservation",
            index=models.Index(
                fields=["card", "-observed_at"], name="catalog_pri_card_id_53972f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="priceobservation",
            index=models.Index(fields=["source"], name="catalog_pri_source_b614bd_idx"),
        ),
        migrations.AddIndex(
            model_name="priceobservation",
            index=models.Index(fields=["grade"], name="catalog_pri_grade_db4d2a_idx"),
        ),
        migrations.AddConstraint(
            model_name="priceobservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__gt", "")),
                fields=("source", "external_id"),
                name="uniq_source_external_id",
            ),
        ),
    ]
