# Generated by Django 5.2.15 on 2026-06-17 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioHolding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text='Grade owned, e.g. "10". Blank for raw.',
                        max_length=10,
                        verbose_name="Grade",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantity"),
                ),
                (
                    "cost_basis",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Per-unit acquisition cost",
                        max_digits=12,
                        verbose_name="Cost Basis (per unit)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "acquired_at",
                    models.DateField(blank=True, null=True, verbose_name="Acquired At"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="catalog.card",
                        verbose_name="Card",
                    ),
                ),
                (
                    "grading_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="holdings",
                        to="catalog.gradingcompany",
                        verbose_name="Grading Company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Holding",
                "verbose_name_plural": "Portfolio Holdings",
                "db_table": "portfolio_holdings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="portfolio_h_user_id_5d019f_idx",
                    ),
                    models.Index(
                        fields=["card"], name="portfolio_h_card_id_fe5c38_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text='Restrict to a grade, e.g. "10". Blank matches any grade.',
                        max_length=10,
                        verbose_name="Grade",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("BELOW", "Price drops to or below"),
                            ("ABOVE", "Price rises to or above"),
                        ],
                        default="BELOW",
                        max_length=10,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "threshold_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Threshold Price"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "triggered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Triggered At"
                    ),
                ),
                (
                    "triggered_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Triggered Price",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_alerts",
                        to="catalog.card",
                        verbose_name="Card",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Alert",
                "verbose_name_plural": "Price Alerts",
                "db_table": "portfolio_price_alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="portfolio_p_user_id_197ecf_idx",
                    ),
                    models.Index(
                        fields=["card", "is_active"],
                        name="portfolio_p_card_id_a2bbb1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WatchlistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_by",
                        to="catalog.card",
                        verbose_name="Card",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Watchlist Item",
                "verbose_name_plural": "Watchlist Items",
                "db_table": "portfolio_watchlist",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="portfolio_w_user_id_0e0394_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "card"), name="uniq_user_card_watch"
                    )
                ],
            },
        ),
    ]
