# Generated by Django 5.2.15 on 2026-06-17 15:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "holdings_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Holdings Count"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Total Cost",
                    ),
                ),
                (
                    "total_market_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Total Market Value",
                    ),
                ),
                (
                    "total_unrealized_pl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Total Unrealized P&L",
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Captured At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_snapshots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Snapshot",
                "verbose_name_plural": "Portfolio Snapshots",
                "db_table": "portfolio_snapshots",
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-captured_at"],
                        name="portfolio_s_user_id_dafbaf_idx",
                    )
                ],
            },
        ),
    ]
